# Generated by Django 5.0.7 on 2024-12-31 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='assigned_judge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='users.judge'),
        ),
        migrations.AddField(
            model_name='case',
            name='assigned_lawyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='users.lawyer'),
        ),
        migrations.AddField(
            model_name='case',
            name='defendant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defendant_cases', to='users.citizen'),
        ),
        migrations.AddField(
            model_name='case',
            name='plaintiff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plaintiff_cases', to='users.citizen'),
        ),
        migrations.AddField(
            model_name='document',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_documents', to='cases.case'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to='users.citizen'),
        ),
        migrations.AddField(
            model_name='hearing',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearings', to='cases.case'),
        ),
    ]
