# Generated by Django 5.0.7 on 2025-01-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hearing',
            name='location',
        ),
        migrations.AddField(
            model_name='hearing',
            name='videocall_link',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
