# Generated by Django 5.0.7 on 2025-01-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='case_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
