# Generated by Django 5.0.7 on 2025-01-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_case_case_description_case_case_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='case_documents/%Y/%m/%d/'),
        ),
    ]
