# Generated by Django 5.0.7 on 2025-01-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_rename_laywer_accepted_case_lawyer_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='defendant_lawyer_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
