# Generated by Django 5.0.7 on 2025-01-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_alter_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='laywer_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
