# Generated by Django 5.0.7 on 2025-01-14 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_case_defendant_lawyer_accepted'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hearing',
            name='assigned_judge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_judge', to='users.judge'),
        ),
    ]
