# Generated by Django 5.0.7 on 2025-01-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_hearing_assigned_judge'),
    ]

    operations = [
        migrations.AddField(
            model_name='hearing',
            name='status',
            field=models.CharField(default='Scheduled', max_length=50),
        ),
    ]
