# Generated by Django 5.0.7 on 2025-01-09 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_case_laywer_accepted'),
        ('users', '0002_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='defendent_lawyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defendent_lawyer', to='users.lawyer'),
        ),
    ]
