# Generated by Django 5.0.7 on 2025-01-14 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_hearing_status'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hearing',
            name='assigned_judge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.judge'),
        ),
    ]
