# Generated by Django 5.1.3 on 2025-01-15 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_alter_hearing_assigned_judge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='defendent_lawyer',
            new_name='defendant_lawyer',
        ),
    ]
