# Generated by Django 5.0.7 on 2025-01-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_rename_defendent_lawyer_case_defendant_lawyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='defendant_lawyer_accepted',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='lawyer_accepted',
            field=models.BooleanField(null=True),
        ),
    ]
