# Generated by Django 5.0.7 on 2025-01-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_alter_case_defendant_lawyer_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='user_type',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
