# Generated by Django 5.0.7 on 2025-01-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_alter_document_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='verdict',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='verdict_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='verdict_time',
            field=models.TimeField(null=True),
        ),
    ]
