# Generated by Django 5.0.7 on 2025-01-14 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
        ('cases', '0004_case_defendant_lawyer_accepted'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=255)),
                ('payment_id', models.CharField(max_length=50)),
                ('signature', models.CharField(max_length=256)),
                ('refund_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=100)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.citizen')),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.lawyer')),
            ],
        ),
    ]
