# Generated by Django 5.0.7 on 2025-01-22 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
