# Generated by Django 5.1.3 on 2025-01-15 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='client',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='lawyer',
        ),
    ]
