# Generated by Django 5.0.7 on 2025-01-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_payment_paid_at_payment_requested_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='email',
            new_name='citizen_email',
        ),
        migrations.AddField(
            model_name='payment',
            name='lawyer_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
